export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS'
export const ERROR_FETCHING_INGS = 'ERROR_FETCHING_INGS'

export const PURCHASE_BURGER_SUCCESS ='PURCHASE_BURGER_SUCCESS' 
export const PURCHASE_BURGER_FAIL ='PURCHASE_BURGER_FAIL'
export const SENDING_ORDER='SENDING_ORDER'
export const REFRESH_REDIRECT_STATUS='REFRESH_REDIRECT_STATUS'

export const FETCH_ORDERS ='FETCH_ORDERS'
export const FETCH_ORDERS_FAILED ='FETCH_ORDERS_FAILED'

export const AUTH_START ='AUTH_START'
export const AUTH_SUCCESS ='AUTH_SUCCESS'
export const AUTH_FAIL ='AUTH_FAIL'
export const LOGOUT_USER ='LOGOUT_USER'
export const RESET_TOTALPRICE ='RESET_TOTALPRICE'
export const SET_AUTH_REDIRECT_PATH ='SET_AUTH_REDIRECT_PATH'